# Generated by Django 5.1.3 on 2024-12-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyumbaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Seller',
        ),
    ]
