# Generated by Django 5.1.3 on 2024-12-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyumbaapp', '0003_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
