# Generated by Django 5.1.3 on 2024-12-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyumbaapp', '0004_alter_house_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='featured_image',
            new_name='image',
        ),
    ]
