# Generated by Django 5.1.3 on 2024-12-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyumbaapp', '0005_rename_featured_image_house_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='House1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('amenities', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='house_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='House',
        ),
    ]
