# Generated by Django 5.1.3 on 2024-12-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyumbaapp', '0006_house1_delete_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house1',
            old_name='image',
            new_name='featured_image',
        ),
    ]
