# Generated by Django 5.1.3 on 2024-12-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyumbaapp', '0007_rename_image_house1_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house1',
            name='amenities',
            field=models.TextField(),
        ),
    ]
